baseURL = "https://jonkeane.com"
languageCode = "en-us"
title = "Jonathan Keane, PhD"
theme = "jonkeane"
googleAnalytics = "G-4G0MWM1GJ4"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
keywords = ["Data science", "predictive models", "statistics", "test driven development", "software carpentry", "data carpentry", "data analysis", "research", "teaching", "linguistics", "ASL", "American Sign Language", "fingerspelling", "phonetics", "syntax", "morphology"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.external]]
    name = "photography"
    url = "https://photo.jonkeane.com"
    weight = 1
[[menu.external]]
    name = "publications"
    url = "https://pubs.jonkeane.com"
    weight = 2
[[menu.external]]
    name = "github"
    url = "https://github.com/jonkeane"
    weight = 3
[[menu.external]]
    name = "email"
    url = "mailto:jkeane@gmail.com"
    weight = 4

[markup]
  [markup.highlight]
    style = "monokailight"

[params]
    description = "Jonathan Keane's Professional Website Data scientist and software developer with a PhD in Linguistics. Interests include data science, software developement, predictive models, articulatory phonetics, and computational approaches to language modeling, sign language phonetics and phonology."
    author = "Jonathan Keane"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "tomorrow"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon folder, under "static"
    favicon = "images/favicons/"


    [params.logo]
    url = "images/jonSquareRev.png"
    alt = "Picture of Jonathan Keane"

