baseURL = "https://jonkeane.com"
languageCode = "en-us"
title = "Jonathan Keane, PhD"
theme = "jonkeane"
googleAnalytics = "G-4G0MWM1GJ4"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
keywords = ["software engineering", "engineering leadership", "test driven development", "performance engineering", "benchmarking", "metric driven development", "continuous integration", "continuous delivery", "data science", "machine learning", "data visualization", "statistics",  "research", "linguistics", "American Sign Language", "fingerspelling", "phonetics"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.external]]
    name = "photography"
    url = "https://photo.jonkeane.com"
    weight = 1
[[menu.external]]
    name = "publications"
    url = "https://pubs.jonkeane.com"
    weight = 2
[[menu.external]]
    name = "github"
    url = "https://github.com/jonkeane"
    weight = 3
[[menu.external]]
    name = "email"
    url = "mailto:jkeane@gmail.com"
    weight = 4

[markup]
  [markup.highlight]
    style = "monokailight"

[params]
    description = "Engineering and Data Science Leader — Interests include: leadership, inclusive teams, CI/CD, test-driven-development, metric-driven-development, performance engineering, data science, and machine learning. Past life: a PhD in Linguistics with a focus on articulatory phonetics, computational approaches to language modeling, and sign language phonetics and phonology."
    author = "Jonathan Keane"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "tomorrow"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon folder, under "static"
    favicon = "images/favicons/"


    [params.logo]
    url = "images/jonSquareRev.png"
    alt = "Picture of Jonathan Keane"

